"""added duration of service

Revision ID: 28f53d7f7e32
Revises: 54010da2a037
Create Date: 2024-11-17 20:04:37.061652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f53d7f7e32'
down_revision: Union[str, None] = '54010da2a037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'card_brand',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('services', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'duration')
    op.alter_column('cards', 'card_brand',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
