"""changed smth

Revision ID: 93c6df799f31
Revises: e61defda1a78
Create Date: 2024-11-25 19:56:50.766183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c6df799f31'
down_revision: Union[str, None] = 'e61defda1a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
