"""changed business and service

Revision ID: c7076e5994a6
Revises: f0851cd86862
Create Date: 2024-11-21 23:41:16.448169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7076e5994a6'
down_revision: Union[str, None] = 'f0851cd86862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('country', sa.String(), nullable=False))
    op.add_column('businesses', sa.Column('city', sa.String(), nullable=False))
    op.add_column('businesses', sa.Column('address', sa.String(), nullable=False))
    op.add_column('businesses', sa.Column('bank_account', sa.String(), nullable=False))
    op.add_column('businesses', sa.Column('bank_account_name', sa.String(), nullable=False))
    op.add_column('businesses', sa.Column('bank_name', sa.String(), nullable=False))
    op.alter_column('services', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_column('services', 'tier')
    op.drop_column('services', 'billing_cycle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('billing_cycle', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('tier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('services', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('businesses', 'bank_name')
    op.drop_column('businesses', 'bank_account_name')
    op.drop_column('businesses', 'bank_account')
    op.drop_column('businesses', 'address')
    op.drop_column('businesses', 'city')
    op.drop_column('businesses', 'country')
    # ### end Alembic commands ###
