"""payouts

Revision ID: d8622e4f0322
Revises: 1d9f28c767b3
Create Date: 2024-11-22 21:11:20.825611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8622e4f0322'
down_revision: Union[str, None] = '1d9f28c767b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.add_column('payouts', sa.Column('business_id', sa.Integer(), nullable=False))
    op.add_column('payouts', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('payouts', sa.Column('payout_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('payouts', sa.Column('status', sa.String(), nullable=False))
    op.drop_constraint('payouts_payout_id_fkey', 'payouts', type_='foreignkey')
    op.drop_constraint('payouts_service_id_fkey', 'payouts', type_='foreignkey')
    op.create_foreign_key(None, 'payouts', 'businesses', ['business_id'], ['business_id'], ondelete='CASCADE')
    op.drop_column('payouts', 'service_id')
    op.add_column('services', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'status')
    op.add_column('payouts', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payouts', type_='foreignkey')
    op.create_foreign_key('payouts_service_id_fkey', 'payouts', 'services', ['service_id'], ['service_id'], ondelete='CASCADE')
    op.create_foreign_key('payouts_payout_id_fkey', 'payouts', 'users', ['payout_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('payouts', 'status')
    op.drop_column('payouts', 'payout_date')
    op.drop_column('payouts', 'amount')
    op.drop_column('payouts', 'business_id')
    op.create_table('votes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], name='votes_service_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='votes_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'service_id', name='votes_pkey')
    )
    # ### end Alembic commands ###
