"""changed smth

Revision ID: e61defda1a78
Revises: c1a8231b4df1
Create Date: 2024-11-25 18:51:57.717529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61defda1a78'
down_revision: Union[str, None] = 'c1a8231b4df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('businesses', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('services', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('services', 'service_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('services', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('businesses', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('businesses', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
