"""changed smth

Revision ID: f0851cd86862
Revises: 28f53d7f7e32
Create Date: 2024-11-17 22:12:08.814520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0851cd86862'
down_revision: Union[str, None] = '28f53d7f7e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('card_brand', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'card_brand')
    # ### end Alembic commands ###
